mail/urls.py
from django.urls import path
from . import views

app_name = 'mail'
urlpatterns = [
    path('mailbox/<int:user_id>/', views.mailbox, name='mailbox'),
    path('send_mail/<int:from_id>/', views.send_mail, name='send_mail'),
    path('delete_mail/<int:mail_id>/', views.delete_mail, name='delete_mail'),
    path('detail_mail/<int:mail_id>/', views.detail_mail, name='detail_mail'),
]

team/urls.py
from django.urls import path
from . import views
app_name = 'team'
urlpatterns = [
    path('create_team/',views.create_team, name='create_team'),
    path('<int:team_id>/', views.detail_team, name="detail_team"),
    path('<int:team_id>/addmember', views.add_member,name="add_member"),
    path('<int:team_id>/<int:user_id>/expulsion_member/', views.expulsion_member, name="expulsion_member"),
    path('<int:team_pk>/<int:user_pk>/leave_team/',views.leave_team, name='leave_team'),
    path('<int:team_pk>/edit_team/', views.edit_team, name='edit_team'),
    path('<int:team_pk>/add_time_table', views.add_time_table, name='add_time_table'),
    path('<int:team_pk>/add_member1', views.add_member1, name='add_member1'),
    path('<int:team_pk>/delete_time_table', views.delete_time_table, name='delete_time_table'),
    path('<int:team_pk>/member_time_table', views.team_user_timetable, name='member_time_table'),
    path('<int:team_pk>/team_meeting_place', views.team_meeting_place, name='team_meeting_place'),
    path('<int:team_pk>/all_team_member', views.all_team_member, name="all_team_member"),
    path('<int:team_pk>/team_chat', views.team_chat, name="team_chat"),
    path('<int:team_pk>/team_chat_delete', views.team_chat_delete, name="team_chat_delete"),
    
]

team_article/urls.py
from django.urls import path
from . import views

app_name = 'team_article'
urlpatterns = [

    path('<int:team_pk>/<int:user_pk>/workspace/', views.workspace, name='workspace'),
    
    path('<int:team_pk>/<int:user_pk>/workspace/url', views.articleurl, name='articleurl'),
    
    path('<int:team_pk>/<int:user_pk>/workspace/file', views.articlefile, name='articlefile'),
    
    path('<int:team_pk>/<int:user_pk>/<int:url_pk>/deleteurl/', views.delete_articleurl, name='delete_articleurl'),
    
    path('<int:team_pk>/<int:user_pk>/<int:file_pk>/deletefile/', views.delete_articlefile, name='delete_articlefile'),

]

teample_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import main.views#메인앱의 views함수를 임포트 해줍니다.

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('mail/', include('mail.urls')),
    path('team/', include('team.urls')),
    path('team_article/', include('team_article.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team/models.py
from django.db import models
from account.models import User

# Create your models here.
class Team(models.Model):
    """
    invitation_code 초대코드를 primary_key로 할까 고민중
    또 어떤 방식으로 생성해야할지 고민중
    """
    # teamChat = models.ForeignKey(TeamChat, on_delete=models.CASCADE)
    team_leader = models.ManyToManyField(User, related_name="leader")
    team_name = models.CharField(blank=False, max_length=20)
    introduce = models.CharField(max_length=200)
    is_active = models.BooleanField(default=True)
    team_photo_url = models.ImageField(upload_to='images/team/{}/'.format(id), blank=True)
    created_date = models.DateTimeField(auto_now_add=True, editable=False)
    members = models.ManyToManyField(User, related_name='members', through='TeamMember')
    # votes = models.IntegerField(default=0)

    # def __str__(self):
    #     return self.team_name

class TeamMember(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return "%s %d %s" % (
            self.team.team_name,
            self.team.id ,
            self.user.username,
            )

class TeamTimeTable(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total_time_table = models.CharField(default=('0' * 91), max_length=91)
    time = models.DateTimeField(auto_now_add=True, editable=False)
    
    # def __str__(self):
    #     return self.total_time_table,self.time
        
class TeamChat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    message = models.CharField(max_length=300)
    send_message = models.DateTimeField(auto_now_add=True, editable=False)

team/forms.py
from django import forms
from account.models import User
from .models import Team, TeamMember, TeamChat
# from team_article.models import Article

class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ['team_name', 'introduce']
        widgets =   { 
            'team_name':forms.TextInput(attrs={'class':'form-control','placeholder': 'team_name'}),
            'introduce':forms.TextInput(attrs={'class':'form-control','placeholder': 'introduce'}) 
            }
        labels = {
            'team_name':'팀 이름',
            'introduce':'팀 소개'
        }
    def chack_team_name(self):
        team_name = self.team_name
        introduce = self.introduce

        if team_name =="" or introduce=="":
            raise forms.ValidationError("팀을 확인해주세요!")

class AddForm(forms.ModelForm):
    username = forms.CharField(max_length=20)
    class Meta:
        model = TeamMember
        fields = ['username']
 
class TeamChatForm(forms.ModelForm):
    class Meta:
        model = TeamChat
        fields = ['message']

team/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from account.models import User
from django.utils import timezone
from .models import Team, TeamMember, TeamTimeTable, TeamChat
from django.contrib.auth.decorators import login_required
from .forms import TeamForm, AddForm
from django.core.paginator import Paginator

import simplejson as json

# Create your views here.

# 2진 데이터를 or로 비교
def or_gate(a, b):      
    result = ""
    for i in range(len(a)):
        if (a[i] == b[i]) and a[i] == '0':
            result += '0'
        else:
            result += '1'

    return result

# 2진 데이터를 not으로 변환
def not_gate(binary):
    result = ""
    for i in binary:
        if i == '1':
            result += '0'
        else:
            result += '1'
    return result

# or게이트와 not게이트를 이용해서 팀에 소속된 유저들의 시간표를 각각 비교해서 원하는 이진데이터를 구함
def get_time_table(team_id):
    team = get_object_or_404(Team, pk=team_id)
    team_members = team.members.all()
    result_time_table = team_members[0].time_table
    for member in team_members[1:]:
        result_time_table = or_gate(result_time_table, member.time_table)

    return not_gate(result_time_table)

@login_required
def detail_team(request, team_id):
   details = get_object_or_404(Team, pk=team_id)
   user = request.user
   user_team = TeamMember.objects.filter(user=user)
   team_member = TeamMember.objects.filter(team=details)
   team_time_table = TeamTimeTable.objects.filter(team=details)
   team_chat = TeamChat.objects.filter(team=details)
   for i in TeamMember.objects.filter(team__pk=details.pk):
      if i.user.pk == user.pk:         
         return render(request, 'team/detail_team.html',{
            'details': details, 
            'team_member':team_member,
            'user':user, 
            'user_team':user_team,
            'team_chat':team_chat,
             })
   
   return redirect('account:user_home', login_user.pk)
   
@login_required
def create_team(request):
   # user = get_object_or_404(User, pk=user_id)
    user = request.user
    data = 0
    if request.method == 'POST':
        form = TeamForm(request.POST)
        if form.is_valid():
            team = form.save()
            TeamMember.objects.create(team=team, user=user)
         # team.members.add(user)
            team.team_leader.add(user)
            team.team_name = form.cleaned_data['team_name']
            team.introduce = form.cleaned_data['introduce']
            team.created_date = timezone.now()
            team.save()
            return redirect('team:detail_team', team.pk)
    # else:
    form = TeamForm()
    return render(request, 'team/create_team.html', {'form': form,'user':user})

@login_required
def add_member(request, team_id):
    team1 = get_object_or_404(Team, pk=team_id)
    login_user = request.user
   
    if request.method == 'POST':
        form = AddForm(request.POST)
        if form.is_valid():
            member = form.save(commit=False)
            member.team = team1 #팀에대한 정보를 가져와 TeamMember의 team 에다가 저장을 하고.
            if User.objects.filter(username=form.cleaned_data['username']):
                member.user = User.objects.get(username=form.cleaned_data['username']) #해당유저에 대한 데이터를 가져오고
                if TeamMember.objects.filter(team=team1, user=member.user).count()>0: #해당 팀에 user가 이미 존재해 있는 경우
                    return HttpResponse('해당사용자가 팀에 존재합니다!')
               
                else: # 해당 팀에 user가 존재하지 않는다면 멤버로 추가
                    tm = TeamMember(team=team1, user=member.user) 
                    tm.save()
                    return redirect('team:detail_team', team_id)
            else:
                return HttpResponse('해당 사용자가 존재하지 않습니다!')
    else:
        for i in TeamMember.objects.filter(team__pk=team1.pk):
            if i.user.pk == login_user.pk: 
                form = AddForm()
                return render(request, 'team/add_member.html', {'form':form})
        return redirect('account:uset_home', login_user.pk)

def add_member1(request, team_pk):
    team = get_object_or_404(Team, pk=team_pk)
    user = request.user
    member = TeamMember()
    invite_username = request.GET['username']
    if User.objects.filter(username=request.GET['username']).count() >0 : #해당 유저 정보가 전체 유저 중에 있을 때 
        invite_user = User.objects.get(username=invite_username)

        if TeamMember.objects.filter(team=team, user=invite_user): # 해당 유저가 팀에 있을 경우
            data = {
                'data' : 1,
                'first_name':invite_user.first_name,
                'last_name':invite_user.last_name
            }
            return HttpResponse(json.dumps(data), content_type='application/json')
            
        else: # 해당 유저가 팀에 없을 경우
            data = {
                'data' : 2,
                'first_name':invite_user.first_name,
                'last_name':invite_user.last_name
            }
            member.team = team
            member.user = invite_user
            member.save()
            return HttpResponse(json.dumps(data), content_type='application/json')
    else:
        data = {
                'data' : 3,
                'first_name':"",
                'last_name':""
            }
        return HttpResponse(json.dumps(data), content_type='application/json')


@login_required
def expulsion_member(request, team_id, user_id):  # 어느 팀에서 몇번 째 유저를 삭제할지.
    login_user = request.user
    team = get_object_or_404(Team, pk=team_id)  # 어느 팀 객체인지 가져오고
    user = get_object_or_404(User, pk=user_id)  # 어느 유저 객체인지 가져온 다음에
    delete_member = TeamMember.objects.filter(team=team, user=user)  # 외래키 설정 되어있는 team과 user 에 각각을 매칭 시켜주기
    delete_member.delete()
    return redirect('team:detail_team', team_id)

@login_required
def leave_team(request, team_pk, user_pk):
    user = get_object_or_404(User, pk=user_pk)
    team = get_object_or_404(Team, pk=team_pk)
    leave = TeamMember.objects.filter(team=team, user=user)
    leave.delete()
    if TeamMember.objects.filter(team__team_name=team.team_name).count() != 0: # 팀 멤버들이 존재한다면!
        if team.team_leader == user:
            if Team.objects.filter(team_leader__pk=user_pk): # 
                next_leader = TeamMember.objects.filter(team__team_name=team.team_name).first()
                leader = get_object_or_404(User, pk=next_leader.user.pk)
                team.team_leader.set([leader])
                team.save()
                return redirect('account:user_home', user_pk)
            return HttpResponse('리더 위임 실패')
        else:
            return redirect('account:user_home', user_pk)
    else:
        team.delete()
        return redirect('account:user_home', user_pk)

def edit_team(request, team_pk):
   team = get_object_or_404(Team, pk=team_pk)
   user = request.user
   if request.method == "POST":
      form = TeamForm(request.POST)
      if form.is_valid():
         team.team_name = form.cleaned_data['team_name']
         team.introduce = form.cleaned_data['introduce']
         team.team_photho_url = form.cleaned_data['team_photo_url']
         team.save()
         return redirect('team:detail_team',team_pk)
   else:
      teamform = TeamForm(instance=team)
      return render(request, 'team/create_team.html', {'teamform':teamform})
    
def add_time_table(request, team_pk):
    team = get_object_or_404(Team, pk=team_pk)
    user = request.user
    data = TeamTimeTable.objects.filter(team=team, user=user).count()
    if data > 0:
        return HttpResponse(json.dumps(data), content_type='application/json')
    else:
        ttt = TeamTimeTable(team=team, user=user, total_time_table=user.time_table)
        ttt.time = timezone.now()
        ttt.save()
        return HttpResponse(json.dumps(data), content_type='application/json')


def delete_time_table(request, team_pk):
    team = get_object_or_404(Team, pk=team_pk)
    user = request.user
    delete_time_table = TeamTimeTable.objects.filter(team=team, user=user)
    data = 0
    if TeamTimeTable.objects.filter(team=team, user=user):
        data = 1  #시간표가 팀 시간에 등록되어있을 경우
        delete_time_table.delete()
        return HttpResponse(json.dumps(data), content_type='application/json')
    else:
        data = 2
        return HttpResponse(json.dumps(data), content_type='application/json')

def team_user_timetable(request, team_pk):
    team = get_object_or_404(Team, pk=team_pk)
    user_team = TeamMember.objects.filter(team=team)
    member_time_table = TeamTimeTable.objects.filter(team=team)
    user = request.user
    user_time_table =  TeamTimeTable.objects.filter(team=team, user=user)
    return render(request, "team/teamtimetable.html",{'user_team':member_time_table, 'user':user, 'team':team,'time':user_time_table})

def team_meeting_place(request, team_pk):
    team = get_object_or_404(Team, pk = team_pk)
    return render(request, "team/team_meeting_place.html",{"team":team})

def all_team_member(request, team_pk):
    team = get_object_or_404(Team, pk=team_pk)
    user_team = TeamMember.objects.filter(team=team)
    return render(request, "team/all_team_member.html", {'user_team':user_team, 'team':team})

def team_chat(request, team_pk):
    user = request.user
    team = get_object_or_404(Team, pk=team_pk)
    data = 0
    chat = TeamChat()
    chat.team = team
    chat.user = user
    chat.message = request.GET['message']
    if chat.message == "":
        context = {'team_pk': team_pk,'data': data,}
        return HttpResponse(json.dumps(context), content_type='application/json')
    else:
        data = 1
        context = {'team_pk': team_pk,'data': data,}
        chat.send_message = timezone.now()
        chat.save()
        # return redirect('team:detail_team', team_pk)
        return HttpResponse(json.dumps(context), content_type='application/json')

def team_chat_delete(request, team_pk):
    team = get_object_or_404(Team, pk = team_pk)
    chat = TeamChat.objects.filter(team=team)
    chat.delete()
    return redirect('team:detail_team', team.pk)

templates/team/create_team.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<!-- <script src="{% static 'js/vendors.bundle.js' %}"></script> -->
<!-- <script src="{% static 'js/app.bundle.js' %}"></script> -->
<script type="text/javascript">

</script>
<div class="container py-4 py-lg-5 my-lg-5 px-4 px-sm-0">
    <div class="row">
        <div class="col-xl-12">
            <h2 class="fs-xxl fw-500 mt-4 text-center" >
                팀을 만들어주세요!
                <small class="h3 fw-300 mt-3 mb-5 opacity-60 hidden-sm-down">
                    팀의 이름과 설명을 써주세요! <br>
                </small>
            </h2>
        </div>
        <div class="col-xl-6 ml-auto mr-auto">
            <div class="card p-4 rounded-plus bg-faded">
                <form id="js-login" novalidate="" method="post">
                        {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ form.team_name.id_for_label }}">팀 이름</label>
                        <input type="text" id="team_name" name="team_name" class="form-control team_create" placeholder="15자 이하..">

                    </div>
                    <div class="form-group">
                        <label for="{{ form.introduce.id_for_label }}">팀 소개</label>
                        <input type="text" id="introduce" name="introduce" class="form-control team_create" placeholder="40자 이하..">
                    </div>
                    <div class="row no-gutters">
                        <div class="col-md-4 ml-auto text-right">
                            <button id="team_create"  class="btn btn-danger" disabled="true" style="background-color: #868b90 bac">생성하기!</button>
                        </div>
                    </div>
                </form>
                
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/team/teamtimetable.html
{% extends 'layout.html' %}

{% block content %}
<style>
td{
    text-align: center;
    
}
</style>
<ol class="breadcrumb page-breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'team:detail_team' team.pk %}">팀으로</a></li>
    <li class="breadcrumb-item"><a href="{% url 'team_article:workspace' team.pk user.pk %}">팀 자료실</a></li>
    <li class="breadcrumb-item"><a href="{% url 'team:team_meeting_place' team.pk %}">팀 모임</a></li>
</ol>

    <div class="subheader">
        <h1 class="subheader-title">
            <i class='subheader-icon fal fa-credit-card-front'></i> 합친 시간표
            <small>
                팀원들이 가능한 시간을 확인할 수 있습니다!
            </small>
        </h1>
    </div>
    
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<div class="row">
<script>
    const arr = new Array(13).fill(0).map(() => new Array(7).fill(0));
    var user_count = 0;
    {% for i in user_team.all %}
    user_count++;
    $( function () {
        var a = "{{ i.total_time_table }}";
        var user_last_name = "{{i.user.last_name}}";
        var user_first_name = "{{i.user.first_name}}";
        let count = 0;
        for (let i = 0; i < 13; i++) {
            for (let j = 0; j < 7; j++) {
                $('#'+i+j).css('font-size','15px');
                if(a.charAt(count) == 0){
                    // $('#'+i+j).text( user_name+"\n"+$('#'+i+j).text());
                    $('#'+i+j).append( user_last_name+user_first_name+"<br>").css('padding-top',(user_count-arr[i][j]) * 10 + 'px');
                    arr[i][j]++;
                }
                count++;
            }
        }
    });
    {% endfor %}
    $(function(){
        if(user_count >= 3){
            for (let i = 0; i < 13; i++) {
                for (let j = 0; j < 7; j++) {
                    if(arr[i][j] === user_count) $('#'+i+j).css('background-color','rgb(177, 221, 253)');// rgb(255, 219, 232)
                    else if(arr[i][j] === user_count-1) $('#'+i+j).css('background-color','rgb(223, 241, 255)');
                    // else if(arr[i][j] === user_count-2) $('#'+i+j).addClass('bg-info-50');
                }
            }
        }
    });
    function team_time_add(team_pk){
        var add_time_table = confirm("팀에 시간표를 추가하시겠습니까?")
        if (add_time_table == true ){
            $.ajax({
                url: '/team/'+team_pk+'/'+'add_time_table',
                success: function(data){
                    if (data > 0){
                        alert("이미 추가된 시간표 입니다!")
                    }
                    else if(data==0){
                        alert("시간표가 성공적으로 추가 되었습니다")
                        // location.href = '/team/'+team_pk;
                        location.href = '/team/'+team_pk+'/'+'member_time_table';
                    }
                },
                error: function(){
                    console.log('실패');
                }
            })
        }
        else return;
    }
    function delete_team_timetable(team_pk){
        var leave_team = confirm("팀에 추가된 시간표를 삭제하시겠습니까?")
        if (leave_team == true){
            $.ajax({
                url: '/team/'+team_pk+'/delete_time_table',
                success: function(data){
                    if (data ==2){
                        alert("추가된 시간표가 존재하지 않습니다");
                    }
                    else if(data==1){
                        alert("시간표가 성공적으로 삭제 되었습니다.");
                        location.href = '/team/'+team_pk + '/member_time_table';
                    }
                },
                error: function(){
                    console.log('실패');
                }
            })
        }
        else return;
    }
    </script>
    <div class="col-sm-12">
        <div class="card mb-g">
            <h5 class="card-header bg-white">
                <span class="fw-300"> <strong>{{team.team_name}}</strong> 전체 시간표 </span>
            </h5>
            <div class="card-body">
                
                <div class="frame-wrap bg-faded mb-1">
                    
                    <div class="custom-checkbox d-inline-flex mr-3">
                        <a onclick="team_time_add('{{ team.pk }}')"style="color: black;">
                        <button type="button" class="btn btn-default" id = "add_button">내 시간표 추가</button></a>
                    </div>
                    <div class=" custom-checkbox d-inline-flex mr-3">
                        <a onclick="delete_team_timetable('{{ team.pk }}')"style="color: black;">
                        <button type="button" class="btn btn-default">내 시간표 삭제</button></a>
                    </div>
                   
                </div>
                <h5 class="frame-heading p-0 bg-white mb-g">
                    {% for time in time.all %}
                   <strong>수정시간:</strong> {{time.time|date:"m-d H:i"}}
                    {% endfor %}
                </h5>
                <div class="frame-wrap p-0 border-0 m-0" >
                    <table class="table m-0 table-bordered table-sm" id="table-example" style="font-size: 20px;">
                        <thead>
                                <tr>
                                    <td id="td_size"></td>
                                    <td>월</td>
                                    <td>화</td>
                                    <td>수</td>
                                    <td>목</td>
                                    <td>금</td>
                                    <td>토</td>
                                    <td>일</td>
                                </tr>
                        </thead>
                        <tbody>
                                <tr>
                                    <td id="td_size">9시</td>
                                    <td id="00"></td> 
                                    <td id="01"></td>
                                    <td id="02"></td>
                                    <td id="03"></td>
                                    <td id="04"></td>
                                    <td id="05"></td>
                                    <td id="06"></td>
                                </tr>
                                <tr>
                                    <td id="td_size">10시</td>
                                    <td id="10"></td>
                                    <td id="11"></td>
                                    <td id="12"></td>
                                    <td id="13"></td>
                                    <td id="14"></td>
                                    <td id="15"></td>
                                    <td id="16"></td>
                                </tr>
                                <tr>
                                    <td id="td_size">11시</td>
                                    <td id="20"></td>
                                    <td id="21"></td>
                                    <td id="22"></td>
                                    <td id="23"></td>
                                    <td id="24"></td>
                                    <td id="25"></td>
                                    <td id="26"></td>
                                </tr>
                                <tr>
                                    <td id="td_size">12시</td>
                                    <td id="30"></td>
                                    <td id="31"></td>
                                    <td id="32"></td>
                                    <td id="33"></td>
                                    <td id="34"></td>
                                    <td id="35"></td>
                                    <td id="36"></td>
                                </tr>
                                <tr>
                                    <td id="td_size">13시</td>
                                    <td id="40"></td>
                                    <td id="41"></td>
                                    <td id="42"></td>
                                    <td id="43"></td>
                                    <td id="44"></td>
                                    <td id="45"></td>
                                    <td id="46"></td>
                                </tr>
                                <tr>
                                    <td id="td_size">14시</td>
                                    <td id="50"></td>
                                    <td id="51"></td>
                                    <td id="52"></td>
                                    <td id="53"></td>
                                    <td id="54"></td>
                                    <td id="55"></td>
                                    <td id="56"></td>
                                </tr>
                                <tr>
                                    <td id="td_size">15시</td>
                                    <td id="60"></td>
                                    <td id="61"></td>
                                    <td id="62"></td>
                                    <td id="63"></td>
                                    <td id="64"></td>
                                    <td id="65"></td>
                                    <td id="66"></td>
                                </tr>
                                <tr>
                                    <td id="td_size">16시</td>
                                    <td id="70"></td>
                                    <td id="71"></td>
                                    <td id="72"></td>
                                    <td id="73"></td>
                                    <td id="74"></td>
                                    <td id="75"></td>
                                    <td id="76"></td>
                                </tr>
                                <tr>
                                    <td id="td_size">17시</td>
                                    <td id="80"></td>
                                    <td id="81"></td>
                                    <td id="82"></td>
                                    <td id="83"></td>
                                    <td id="84"></td>
                                    <td id="85"></td>
                                    <td id="86"></td>
                                </tr>
                                <tr>
                                    <td id="td_size">18시</td>
                                    <td id="90"></td>
                                    <td id="91"></td>
                                    <td id="92"></td>
                                    <td id="93"></td>
                                    <td id="94"></td>
                                    <td id="95"></td>
                                    <td id="96"></td>
                                </tr>
                                <tr>
                                    <td id="td_size">19시</td>
                                    <td id="100"></td>
                                    <td id="101"></td>
                                    <td id="102"></td>
                                    <td id="103"></td>
                                    <td id="104"></td>
                                    <td id="105"></td>
                                    <td id="106"></td>
                                </tr>
                                <tr>
                                    <td id="td_size">20시</td>
                                    <td id="110"></td>
                                    <td id="111"></td>
                                    <td id="112"></td>
                                    <td id="113"></td>
                                    <td id="114"></td>
                                    <td id="115"></td>
                                    <td id="116"></td>
                                </tr>
                                <tr>
                                    <td id="td_size">21시</td>
                                    <td id="120"></td>
                                    <td id="121"></td>
                                    <td id="122"></td>
                                    <td id="123"></td>
                                    <td id="124"></td>
                                    <td id="125"></td>
                                    <td id="126"></td>
                                </tr>
                            </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $('input:checkbox').change(function()
    {
        if ($(this).is(":checked"))
        {
            $('#table-example').addClass($(this).attr("data-class"));
        }
        else
        {
            $('#table-example').removeClass($(this).attr("data-class"));
        }
    });

</script>
{% endblock %}