mail/urls.py
from django.urls import path
from . import views

app_name = 'mail'
urlpatterns = [
    path('mailbox/<int:user_id>/', views.mailbox, name='mailbox'),
    path('send_mail/<int:from_id>/', views.send_mail, name='send_mail'),
    path('delete_mail/<int:mail_id>/', views.delete_mail, name='delete_mail'),
    path('detail_mail/<int:mail_id>/', views.detail_mail, name='detail_mail'),
]

team/urls.py
from django.urls import path
from . import views
app_name = 'team'
urlpatterns = [
    path('create_team/',views.create_team, name='create_team'),
    path('<int:team_id>/', views.detail_team, name="detail_team"),
    path('<int:team_id>/addmember', views.add_member,name="add_member"),
    path('<int:team_id>/<int:user_id>/expulsion_member/', views.expulsion_member, name="expulsion_member"),
    path('<int:team_pk>/<int:user_pk>/leave_team/',views.leave_team, name='leave_team'),
    path('<int:team_pk>/edit_team/', views.edit_team, name='edit_team'),
    path('<int:team_pk>/add_time_table', views.add_time_table, name='add_time_table'),
    path('<int:team_pk>/add_member1', views.add_member1, name='add_member1'),
    path('<int:team_pk>/delete_time_table', views.delete_time_table, name='delete_time_table'),
    path('<int:team_pk>/member_time_table', views.team_user_timetable, name='member_time_table'),
    path('<int:team_pk>/team_meeting_place', views.team_meeting_place, name='team_meeting_place'),
    path('<int:team_pk>/all_team_member', views.all_team_member, name="all_team_member"),
    path('<int:team_pk>/team_chat', views.team_chat, name="team_chat"),
    path('<int:team_pk>/team_chat_delete', views.team_chat_delete, name="team_chat_delete"),
    
]

team_article/urls.py
from django.urls import path
from . import views

app_name = 'team_article'
urlpatterns = [

    path('<int:team_pk>/<int:user_pk>/workspace/', views.workspace, name='workspace'),
    
    path('<int:team_pk>/<int:user_pk>/workspace/url', views.articleurl, name='articleurl'),
    
    path('<int:team_pk>/<int:user_pk>/workspace/file', views.articlefile, name='articlefile'),
    
    path('<int:team_pk>/<int:user_pk>/<int:url_pk>/deleteurl/', views.delete_articleurl, name='delete_articleurl'),
    
    path('<int:team_pk>/<int:user_pk>/<int:file_pk>/deletefile/', views.delete_articlefile, name='delete_articlefile'),

]

teample_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import main.views#메인앱의 views함수를 임포트 해줍니다.

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('mail/', include('mail.urls')),
    path('team/', include('team.urls')),
    path('team_article/', include('team_article.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team_article/models.py
from django.db import models
from team.models import Team
from account.models import User
import os

def article_file_name(fileUrl):
    a = 0
    for i in range(len(fileUrl)):
        if fileUrl[i] == '/':
            a = i
    return a

# Create your models here.
def article_file_path(instance, filename):
    return 'articlefile/{}/{}/files/{}'.format(instance.team.team_name, instance.user.username, filename)


def article_image_path(instance, filename):
    return 'articles/{}/images/{}'.format(instance.article.pk, filename)


def comment_file_path(instance, filename):
    return 'articles/{}/comment/{}/files/{}'.format(instance.comment.article.pk, instance.comment.pk, filename)


def comment_image_path(instance, filename):
    return 'articles/{}/comment/{}/images/{}'.format(instance.comment.article.pk, instance.comment.pk, filename)



class ArticleFile(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    file_url = models.FileField(upload_to=article_file_path)
    explain_content = models.CharField(max_length=300)
    created_date = models.DateTimeField(auto_now_add=True, editable=False)
    modified_date = models.DateTimeField(auto_now=True)

    def summary(self):
        return self.file_url.name[article_file_name(self.file_url.name)+1:]
    
    def __str__(self):
        return self.explain_content
    
class ArticleUrl(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    url = models.URLField(max_length=300)
    explain_content = models.CharField(max_length=300)
    created_date = models.DateTimeField(auto_now_add=True, editable=False)
    modified_date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.explain_content

    def summary(self):
        return self.url[0:15]
    
class CommentUrl(models.Model):
    articleurl = models.ForeignKey(ArticleUrl, on_delete=models.CASCADE)
    post_user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True, editable=False)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

class CommentFile(models.Model):
    articlefile = models.ForeignKey(ArticleFile, on_delete=models.CASCADE)
    post_user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True, editable=False)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content


# class ArticleImage(models.Model):
#     article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='images')
#     image_url = models.FileField(upload_to=article_image_path)
#     explain_content = models.CharField(max_length=300)
#     created_date = models.DateTimeField(auto_now_add=True, editable=False)
#     modified_date = models.DateTimeField(auto_now=True)

team_article/forms.py
from django import forms
from .models import ArticleFile, ArticleUrl

# file_url = models.FileField(upload_to=article_file_path)
# image_url = models.FileField(upload_to=article_image_path)
# url = models.URLField(max_length=300)

class ArticleFileForm(forms.ModelForm):
    class Meta:
        model = ArticleFile
        fields = ['file_url','explain_content']
        widgets = {
            'file_url':forms.FileInput(attrs={'class':'form-control','placeholder': 'file_url'}),
            'explain_content':forms.TextInput(attrs={'class':'form-control', 'placeholder': 'explain_content'})
        }
        labels = {
            'file_url':'파일',
            'explain_content':'파일 설명'
        }

class ArticleUrlForm(forms.ModelForm):
    class Meta:
        model = ArticleUrl
        fields = ['url','explain_content']
        widgets = {
            'url':forms.TextInput(attrs={'class':'form-control', 'placeholder':'url'}),
            'explain_content':forms.TextInput(attrs={'class':'form-control', 'placeholder':'explain_content'})
        }
        labels = {
            'url':'주소',
            'explain_content':'주소 설명'
        }

team_article/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import ArticleFile, ArticleUrl, CommentUrl
from .forms import ArticleFileForm, ArticleUrlForm
from team.models import Team, TeamMember
from account.models import User
from django.core.paginator import Paginator

from django.utils import timezone

# Create your views here.
def workspace(request, team_pk, user_pk):
    team = get_object_or_404(Team, pk=team_pk) #팀에 대한 정보를 가져오고
    # user = get_object_or_404(User, pk=user_pk) #사용자에 대한 정보를 가져오고
    now_user = get_object_or_404(User, pk=user_pk)
    member = TeamMember.objects.filter(team=team)
    user = request.user    
    urlform = ArticleUrlForm()
    fileform = ArticleFileForm()
#     ur = 'https://docs.djangoproject.com/en/2.2/ref/templates/builtins/' 
    search_url = ArticleUrl.objects.filter(team=team, user=now_user)
    url_paginator = Paginator(search_url,6)
    url_page_number = request.GET.get('page',1)
    url_page_obj = url_paginator.get_page(url_page_number)

    if TeamMember.objects.filter(team=team, user=user).exists():
        search_file = ArticleFile.objects.filter(team=team, user=now_user)
        file_list = search_file
        return render(request, 'team_article/workspace.html', {
            'search_url':search_url, 
            'search_file':search_file, 
            'team':team, 'user':user,
            'urlform':urlform,
            'now_user':now_user,
            'fileform':fileform,
            'user_team':member,
            'member':member,
            'url_page_obj':url_page_obj,
            })
    else:
        return redirect('account:user_home', user.pk)
def articleurl(request, team_pk, user_pk):
    team = get_object_or_404(Team, pk=team_pk)
    user = get_object_or_404(User, pk=user_pk)
    if request.method == "POST":
        form = ArticleUrlForm(request.POST)
        if form.is_valid():
            articleurl = form.save(commit=False)
            articleurl.created_date = timezone.now()
            articleurl.team = team
            articleurl.user = user
            articleurl.url = form.cleaned_data['url']
            articleurl.explain_content = form.cleaned_data['explain_content']
            articleurl.save()
            return redirect('team_article:workspace', team_pk, user_pk)

    else:
        form = ArticleUrlForm()
        return render(request, 'team_article/url.html', {'form': form})

def articlefile(request, team_pk, user_pk):
    team = get_object_or_404(Team, pk=team_pk)
    user = get_object_or_404(User, pk=user_pk)
    if request.method == "POST":
        form = ArticleFileForm(request.POST, request.FILES)
        if form.is_valid():
            articlefiles = form.save(commit=False)
            articlefiles.team = team
            articlefiles.user = user
            articlefiles.file_url = form.cleaned_data['file_url']
            articlefiles.explain_content = form.cleaned_data['explain_content']
            articlefiles.created_date = timezone.now()
            articlefiles.save()
            return redirect('team_article:workspace', team_pk, user_pk)
    
    else:
        form = ArticleFileForm()
        return(request, 'team_article/file.html', {'form':form})


def delete_articleurl(request, team_pk, user_pk, url_pk):
    if request.user.pk == user_pk:
        url = ArticleUrl.objects.filter(pk=url_pk)
        url.delete()
        return redirect('team_article:workspace', team_pk, user_pk)
    else:
        return redirect('account:user_home', request.user.pk)

def delete_articlefile(request, team_pk, user_pk, file_pk):
    if request.user.pk == user_pk:
        files = ArticleFile.objects.filter(pk=file_pk)
        files.delete()
        return redirect('team_article:workspace', team_pk, user_pk)
    else:
        return redirect('account:user_home', request.user.pk)

templates/team_article/QQ_workspace.html
{% extends 'layout.html' %}
{% block content %}
<style>
.inner-block {
    padding: 6em 2em 4em 2em;
    background: #fafafa;
}
#td_a{
    color: black;
}
</style>
<div class="col-md-12">
<table style="margin-bottom: 30px;">
<tr>
    {% for members in user_team.all %}
    <td style="padding-left: 10px; padding-right: 15px;" id="td_a"><a href="{% url 'team_article:workspace' members.team.pk members.user.pk %}" style="color: black; font-size: 15px;">{{ members.user.username }}의 작업공간</a></td>
    {% endfor %}
    <td><a href="{% url 'team:detail_team' team.pk %}" style="color: rgb(0, 0, 0);">Team Home</a></td>
</tr>
</table>  
        <div class="col-md-6" style="padding:15px; margin-bottom: 20px;background-color:white; border: 1px solid rgb(238, 232, 232); overflow: hidden;
        height: auto;">
            <form action="{% url 'team_article:articleurl' team.pk user.pk %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                        <label for="{{ urlform.url.id_for_label }}">주소</label>
                        {{ urlform.url }}
                    </div>
                    <div class="form-group">
                        <label for="{{ urlform.explain_content.id_for_label }}">주소 설명</label>
                        {{ urlform.explain_content }}
                    </div>
                    <div class="forgot-top-grids">
                        <div class="clearfix"> </div>
                    </div>
                    <input type="submit" name="Sign In" value="저장">	
            </form>
        </div>
        <div class="col-md-6" style="padding:15px; margin-bottom: 20px;background-color: white; border: 1px solid rgb(238, 232, 232); ">
                <form action="{% url 'team_article:articlefile' team.pk user.pk %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                            <label for="{{ fileform.file_url.id_for_label }}">파일</label>
                            {{ fileform.file_url }}
                        </div>
                        <div class="form-group">
                            <label for="{{ fileform.explain_content.id_for_label }}">파일 설명</label>
                            {{ fileform.explain_content }}
                        </div>
                        <div class="forgot-top-grids">
            
            
                            <div class="clearfix"> </div>
                        </div>
                        <input type="submit" name="Sign In" value="저장">	
                </form>
            </div>
    </div>
<br>

<div class="col-md-12" style="margin: 20px; border: 1px solid rgb(238, 232, 232); overflow: hidden; height: auto;">
    <div class="col-md-6" style="padding: 15px; word-break:break-all;">
        <h1>주소 게시판</h1>
        <hr>
            {% for i in search_url.all %}
            <div class=card>
            주소: <a href="{{ i.url }}" target="_blank">{{ i.summary }}...</a><br>
            설명:{{ i.explain_content}}
            <br>
            {{i.created_date }}
            {% if user.id == now_user.id %}
            <a href="{% url 'team_article:delete_articleurl' team.pk user.pk i.pk %}">삭제</a>
            {% endif %}
        </div>
            <br><br><br>
            {% endfor %}
    </div>
    <div class="col-md-6 "style="padding: 15px;">
        <h1>파일 게시판</h1>
        <hr>
        {% for i in search_file.all %}
        <br>
        <a href="{{ i.file_url.url }}" download>{{ i.file_url.name }}</a>
        {% if user.id == now_user.id %}
        <a href="{% url 'team_article:delete_articlefile' team.pk user.pk i.pk %}">삭제</a>
        {% endif %}
        <br>
        설명: {{i.explain_content}}
        <br>
        {% endfor %}
    </div>
</div>
{% endblock%}

templates/team_article/workspace.html
{% extends 'layout.html' %}
{% block content %}


<ol class="breadcrumb page-breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'team:detail_team' team.pk %}">팀으로</a></li>
    <li class="breadcrumb-item"><a href="{% url 'team:member_time_table' team.pk %}">팀 시간표</a></li>
    <li class="breadcrumb-item"><a href="{% url 'team:team_meeting_place' team.pk %}">모임 장소</a></li>
</ol>

    <div class="subheader">
        <h1 class="subheader-title">
            <i class='subheader-icon fal fa-credit-card-front'></i> {{team.team_name}}
            <small>
                당신의 자료들을 보관, 공유해주세요!
            </small>
        </h1>
    </div>
    
    <div class="row">
        <div class="col-xl-6">
            <div id="panel-1" class="panel">
                <div class="panel-hdr">
                    <h2>
                        주소 <span class="fw-300"><i>inputs</i></span>
                    </h2>
                    <div class="panel-toolbar">
                    </div>
                </div>
                <div class="panel-container show">
                    <div class="panel-content">
                        <div class="panel-tag">
                            찾은 주소를 입력하고 자료에 대한 설명을 쓰고 저장하면 밑에 자료들이 쌓입니다!
                        </div>
                        <form action="{% url 'team_article:articleurl' team.pk user.pk %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                    <label for="{{ urlform.url.id_for_label }}">주소</label>
                                    {{ urlform.url }}
                            </div>
                           
                            <div class="form-group">
                                <!-- <label class="form-label" for="example-textarea">Text area</label>
                                <textarea class="form-control" id="example-textarea" rows="3"></textarea> -->
                            <label for="{{ urlform.explain_content.id_for_label }}">주소 설명</label>
                        {{ urlform.explain_content }}
                            </div>
                            <div class="panel-toolbar">
                                <button type="submit" class="btn btn-default btn-pills">저장</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-6">
            <div id="panel-1" class="panel">
                <div class="panel-hdr">
                    <h2>
                        파일 <span class="fw-300"><i>inputs</i></span>
                    </h2>
                    <div class="panel-toolbar">
                    </div>
                </div>
                <div class="panel-container show">
                    <div class="panel-content">
                        <div class="panel-tag">
                            업로드할 파일을 올리고 저장을 눌러주세요!    
                        </div>
                        <form action="{% url 'team_article:articlefile' team.pk user.pk %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                    <label class="form-label">File (Browser)</label>
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="file_url" name="file_url">
                                    <label class="custom-file-label" for="{{ fileform.file_url.id_for_label }}">Choose file</label>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="{{ fileform.explain_content.id_for_label }}">파일 설명</label>
                                {{ fileform.explain_content }}
                            </div>
                            <div class="panel-toolbar">
                                <button type="submit" class="btn btn-default btn-pills">저장</button>                   
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12">
            <div id="panel-1" class="panel">
                <div class="panel-hdr">
                    <h2>
                        {{now_user.username}} <span class="fw-300"><i>님의 자료실입니다</i></span>
                    </h2>
                    <div class="btn-group">
                        <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{user.username}}
                        </button>
                        <div class="dropdown-menu">
                            {% for members in member %}
                            <a class="dropdown-item" href="{% url 'team_article:workspace' members.team.pk members.user.pk %}" sec>{{members.user.username}}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="row">
                <div class="col-6 .col-sm-6">
                    <div class="panel-hdr">
                        <h2 data-filter-tags="hover background">
                            
                             <span class="fw-300"><i>저장한 주소들의 정보입니다!</i></span>
                        </h2>
                        
                    </div>
                    <div class="panel-container show">
                        <div class="panel-content">
                            <div class="panel-tag">
                                클릭시 해당 주소로 페이지가 이동합니다!
                            </div>
                            <div class="row">
                                    {% for i in url_page_obj %}
                                <div class="col-sm-6 col-md-6 col-xl-4">
                                    <div class="rounded mb-g border border-faded  color-fusion-300">
                                        <div class="p-3 rounded">
                                            <strong>주소</strong>
                                            <p>
                                                <a href="{{ i.url }}" target="_blank">{{ i.summary }}...</a>
                                            </p>
                                            설명
                                            <p>
                                                <strong>{{ i.explain_content}}</strong>
                                            </p>                                            <p>
                                                    {{i.created_date| date:"m-d H:i" }}
                                            </p>
                                            {% if user.id == now_user.id %}
                                            <a href="{% url 'team_article:delete_articleurl' team.pk user.pk i.pk %}">삭제</a>
                                            {% endif %}                                        
                                        </div>
                                    </div>
                                   
                                </div>
                                {% endfor %}
                                
                            </div>
                            {% if url_page_obj %}
                                
                                {% if url_page_obj.has_previous %}
                                    <a href="?page=1">&laquo; first</a>
                                    <a href="?page={{ url_page_obj.previous_page_number }}">previous</a>
                                {% endif %}

                                <span class="current">
                                    Page {{ url_page_obj.number }} of {{ url_page_obj.paginator.num_pages }}.
                                </span>

                                {% if url_page_obj.has_next %}
                                    <a href="?page={{ url_page_obj.next_page_number }}">next</a>
                                    <a href="?page={{ url_page_obj.paginator.num_pages }}">last &raquo;</a>
                                {% endif %}

                            {% endif %}
                            </div>
                    </div>
                </div>
                <div id="panel-5" class="col-6 .col-sm-6">
                    <div class="panel-hdr">
                        <h2 data-filter-tags="hover background">
                            <span class="fw-300"><i>저장한 파일 목록입니다!</i></span>
                        </h2>
                        
                    </div>
                    <div class="panel-container show">
                        <div class="panel-content">
                            <div class="panel-tag">
                                클릭시 해당 파일이 다운로드 됩니다!
                            </div>
                            <div class="row">
                                    {% for i in search_file.all %}
                                <div class="col-sm-6 col-md-6 col-xl-4">
                                        <div class="rounded mb-g border border-faded  color-fusion-300">
                                        <div class="p-3 rounded">
                                            <strong>파일이름</strong>
                                            <p>
                                                <a href="{{ i.file_url.url }}" download>{{i.summary}}</a>
                                            </p>
                                            <strong>설명</strong>
                                            <p>
                                                    {{i.explain_content}}
                                            </p>
                                            <p>
                                                
                                            </p>
                                            {% if user.id == now_user.id %}
                                            <a href="{% url 'team_article:delete_articlefile' team.pk user.pk i.pk %}">삭제</a>
                                            {{i.created_date| date:"m-d H:i"}}
                                            {% endif %}
                                        </div>
                                    </div>
                               </div>
                               {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
{% endblock %}