account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('edit_user/', views.edit_user, name='edit_user'),
    path('user_home/<int:user_pk>', views.user_home, name='user_home'),
    path('user_info/<int:user_pk>', views.user_info, name='user_info'),
    path('schedule/', views.set_schedule, name='set_schedule'),
    path('user_team/<int:user_pk>', views.user_team, name='user_team'),
    path('overlap_username/',views.overlap_username, name="overlap_username"),
    
]

mail/urls.py
from django.urls import path
from . import views

app_name = 'mail'
urlpatterns = [
    path('mailbox/<int:user_id>/', views.mailbox, name='mailbox'),
    path('send_mail/<int:from_id>/', views.send_mail, name='send_mail'),
    path('delete_mail/<int:mail_id>/', views.delete_mail, name='delete_mail'),
    path('detail_mail/<int:mail_id>/', views.detail_mail, name='detail_mail'),
]

team/urls.py
from django.urls import path
from . import views
app_name = 'team'
urlpatterns = [
    path('create_team/',views.create_team, name='create_team'),
    path('<int:team_id>/', views.detail_team, name="detail_team"),
    path('<int:team_id>/addmember', views.add_member,name="add_member"),
    path('<int:team_id>/<int:user_id>/expulsion_member/', views.expulsion_member, name="expulsion_member"),
    path('<int:team_pk>/<int:user_pk>/leave_team/',views.leave_team, name='leave_team'),
    path('<int:team_pk>/edit_team/', views.edit_team, name='edit_team'),
    path('<int:team_pk>/add_time_table', views.add_time_table, name='add_time_table'),
    path('<int:team_pk>/add_member1', views.add_member1, name='add_member1'),
    path('<int:team_pk>/delete_time_table', views.delete_time_table, name='delete_time_table'),
    path('<int:team_pk>/member_time_table', views.team_user_timetable, name='member_time_table'),
    path('<int:team_pk>/team_meeting_place', views.team_meeting_place, name='team_meeting_place'),
    path('<int:team_pk>/all_team_member', views.all_team_member, name="all_team_member"),
    path('<int:team_pk>/team_chat', views.team_chat, name="team_chat"),
    path('<int:team_pk>/team_chat_delete', views.team_chat_delete, name="team_chat_delete"),
    
]

teample_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import main.views#메인앱의 views함수를 임포트 해줍니다.

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('mail/', include('mail.urls')),
    path('team/', include('team.urls')),
    path('team_article/', include('team_article.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/변경전layout.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
    <title>Teample</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Shoppy Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all">
{#    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">#}
    <!-- Custom Theme files -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <!--js-->
    <script src="{% static 'js/jquery-2.1.1.min.js' %}"></script>
    <!--icons-css-->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <!--Google Fonts-->
    <link href='https://fonts.googleapis.com/css?family=Carrois+Gothic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500,600' rel='stylesheet' type='text/css'>
    <!-- 합쳐지고 최소화된 최신 CSS -->

    <!--//skycons-icons-->
    {#    프로젝트 css#}
    <link rel="stylesheet" href="{% static 'account/sign_in.css' %}">
    <link rel="stylesheet" href="{% static 'account/sign_up.css' %}">
</head>
<body>
<div class="page-container">
    <div class="left-content">
        <div class="mother-grid-inner">
            <!--header start here-->
            <div class="header-main" style="background: #f5f5f5;">
                <div class="header-left">
                    <div class="logo-name">
                        <a href="{% url 'account:user_home' user.pk %}"> <h1>Teample</h1>
                            <!--<img id="logo" src="" alt="Logo"/>-->
                        </a>
                    </div>
                    <!--search-box-->
                   
                    <div class="clearfix"> </div>
                </div>
                <div class="header-right">
                    
                    <!--notification menu end -->
                    <div class="profile_details">
                        <ul>
                            <li class="dropdown profile_details_drop">
                                {% if user.is_active %}
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                        <div class="profile_img">
                                            <div class="user-name">
                                                <p>{{ user.username }} 님</p>
                                                <span>환영합니다!</span>
                                            </div>
                                            <i class="fa fa-angle-down lnr"></i>
                                            <i class="fa fa-angle-up lnr"></i>
                                            <div class="clearfix"></div>
                                        </div>
                                    </a>
                                    <ul class="dropdown-menu drp-mnu">
                                        <li> <a href="#"><i class="fa fa-cog"></i> Settings</a> </li>
                                        <li> <a href="#"><i class="fa fa-user"></i> Profile</a> </li>
                                        <li> <a href="{% url 'account:sign_out' %}"><i class="fa fa-sign-out"></i>로그아웃</a></li>
                                    </ul>
                                {% else %}
                                    <div class="profile_img">
                                        <div class="user-name">
                                            {
                                            <h4><p><i class="fa fa-sign-out"></i><a href="{% url 'account:sign_in' %}"> 로그인</a></p></h4>
                                            <h4><p><i class="fa fa-user"></i><a href="{% url 'account:sign_up' %}"> 회원가입</a></p></h4>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                {% endif %}
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"> </div>
                </div>
                <div class="clearfix"> </div>
            </div>
            <!--heder end here-->
            <!-- script-for sticky-nav -->
            <script>
                $(document).ready(function() {
                    var navoffeset=$(".header-main").offset().top;
                    $(window).scroll(function(){
                        var scrollpos=$(window).scrollTop();
                        if(scrollpos >=navoffeset){
                            $(".header-main").addClass("fixed");
                        }else{
                            $(".header-main").removeClass("fixed");
                        }
                    });

                });
            </script>
            <!-- /script-for sticky-nav -->
            <!--inner block start here-->
            <div class="inner-block" style="background: #ffffff; overflow:hidden; height:auto;">
                <div class="blank" style="overflow:hidden; height:auto;">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
            <!--inner block end here-->
            <!--copy rights start here-->

            <!--COPY rights end here-->
        </div>
        <div class="copyrights">
                <p>© 2019 정보통신공학과 캡스톤 </p>
           </div>	
    </div>
    <!--slider menu-->
    <div class="sidebar-menu" style="background-color: #4e5050; " >

        <div class="menu">
            <ul id="menu" >
                <li id="menu-home" ><a href="{% url 'account:user_home' user.pk %}" ><i class="glyphicon glyphicon-home" aria-hidden="true" style="color: white;"></i><span>home</span></a></li>
                <li><a href="{% url 'account:set_schedule' %}"><i class="glyphicon glyphicon-list-alt" aria-hidden="true" style="color: white;"></i><span>내 시간표</span></a></li>
                <li><a href="{% url 'team:create_team' %}"><i class="glyphicon glyphicon-plus" aria-hidden="true" style="color: white;"></i><span>Create Team!</span></a></li>
                
                
                {% if user.is_active %}
                <li><a href="{% url 'mail:mailbox' user.id %}"><i class="fa fa-envelope"></i><span>Mailbox</span><span class="fa fa-angle-right" style="float: right"></span></a>
                    <ul id="menu-academico-sub" >
                    </ul>
                </li>
                {% endif %}
                
            </ul>
        </div>
    </div>
    <div class="clearfix"> </div>
</div>

<!--slide bar menu end here-->
<script>
    var toggle = true;

    $(".sidebar-icon").click(function() {
        if (toggle)
        {
            $(".page-container").addClass("sidebar-collapsed").removeClass("sidebar-collapsed-back");
            $("#menu span").css({"position":"absolute"});
        }
        else
        {
            $(".page-container").removeClass("sidebar-collapsed").addClass("sidebar-collapsed-back");
            setTimeout(function() {
                $("#menu span").css({"position":"relative"});
            }, 400);
        }
        toggle = !toggle;
    });
</script>
<!--scrolling js-->
<script src="{% static 'js/jquery.nicescroll.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>
<!--//scrolling js-->
<script src="{% static 'js/bootstrap.js' %}"> </script>
<!-- mother grid end here-->
</body>
</html>


                      
						